// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAU-y_7YrX51NATg1tRzYH1yxUkIyvCAI',
    appId: '1:191872581619:web:ed6c2f64980e0c7b1a9c86',
    messagingSenderId: '191872581619',
    projectId: 'chat-app-cf951',
    authDomain: 'chat-app-cf951.firebaseapp.com',
    storageBucket: 'chat-app-cf951.firebasestorage.app',
    measurementId: 'G-Y7HJ7YG2ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnymze6Vz3xAptt-bUkwKFRSbJdM21L4',
    appId: '1:191872581619:android:8610e05991f9212f1a9c86',
    messagingSenderId: '191872581619',
    projectId: 'chat-app-cf951',
    storageBucket: 'chat-app-cf951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-Fv0xh-ML08hvq9dxfO4na8O3KsxOVc',
    appId: '1:191872581619:ios:d256b465b45300ae1a9c86',
    messagingSenderId: '191872581619',
    projectId: 'chat-app-cf951',
    storageBucket: 'chat-app-cf951.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAU-y_7YrX51NATg1tRzYH1yxUkIyvCAI',
    appId: '1:191872581619:web:c3e97d62f152566c1a9c86',
    messagingSenderId: '191872581619',
    projectId: 'chat-app-cf951',
    authDomain: 'chat-app-cf951.firebaseapp.com',
    storageBucket: 'chat-app-cf951.firebasestorage.app',
    measurementId: 'G-MKR6FFQG8B',
  );

}